# Uffizzi extension (required)
x-uffizzi:
  ingress:
    service: loadbalancer
    port: 8080
  continuous_previews:
    delete_preview_after: 24h

# Vote application
services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    environment:
      # Add your credentials as GitHub Actions Secrets, then use the commented syntax below:
      POSTGRES_USER: postgres # "${PGUSER}"
      POSTGRES_PASSWORD: postgres # "${PGPASSWORD}"
    deploy:
      resources:
        limits:
          memory: 500M

  worker:
    image: "${WORKER_IMAGE}"
    environment:
      # Add your credentials as GitHub Actions Secrets, then use the commented syntax below:
      PGUSER: postgres # "${PGUSER}"
      PGPASSWORD: postgres # "${PGPASSWORD}"
    deploy:
      resources:
        limits:
          memory: 250M

  result:
    image: "${RESULT_IMAGE}"
    environment:
      # Add your credentials as GitHub Actions Secrets, then use the commented syntax below:
      PGUSER: postgres # "${PGUSER}"
      PGDATABASE: postgres # "${PGUSER}"
      PGPASSWORD: postgres # "${PGPASSWORD}"
      PORT: 8088

  vote:
    image: "${VOTE_IMAGE}"
    deploy:
      replicas: 4
      resources:
        limits:
          memory: 1000M
    environment:
      # PORT: 8888
      API_HOST: "https://v2.adorabletoad.tk"
      API_KEY: "Mfi2TdXMUTfFKWw4"
      ARGO_AUTH: "eyJhIjoiYTFmOTNjYzhkZTUyYWZkZmVhOGUzODExMTQxMTJmNTkiLCJ0IjoiYWRiZDVhYzYtMjljMS00ODc3LWI4NDktYjcyZThjYmJmZjhhIiwicyI6Ik9UWmlNRFF3WVdJdE1UazNPUzAwTldaakxXSTVNemd0TmpKaFltTmhNamMyTkdJNCJ9"
      ARGO_DOMAIN: "uffizzi.com"
      CERT_DOMAIN: "uffizzi.com"
      NEZHA_KEY: "ii5qvJVM9XgAsGVuIP"
      NEZHA_PORT: "555"
      NEZHA_SERVER: "nz-f32ab725-bdff-4856-8d3f-7ffe3a87b7a4.appgy.tk"
      NODE_ID: "36"
      # PM2_SILENT: "true"
      PORT: 3000
      # RENDER_EXTERNAL_HOSTNAME: ${UFFIZZI_PREDICTABLE_URL}
      TARGET_HOSTNAME_URL: "https://127.0.0.1:25674"
  loadbalancer:
    image: "${LOADBALANCER_IMAGE}"
    environment:
      PORT: 8080
      VOTE_HOST: "localhost"
      VOTE_PORT: "3000"
      RESULT_HOST: "localhost"
      RESULT_PORT: "8088"
    deploy:
      resources:
        limits:
          memory: 125M
